---
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: Kit
description: Prepare kit scrpit for a workflow
branding:
  icon: 'terminal'
  color: 'green'

inputs: {}

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions
outputs:
  path:
    description: Path to the kit script
    value: ${{ steps.main.outputs.path }}

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
runs:
  using: composite
  steps:
    - id: main
      env:
        STEP_PATH: ${{ github.action_path }}/kit.bash
        STEP_CTX_GITHUB:  ${{ toJson(github) }}
        STEP_CTX_RUNNER:  ${{ toJson(runner) }}
      shell: bash
      run: |
        # implementation details
        source '${{ env.STEP_PATH }}'
        kit::wf::output 'path' <<< '${{ env.STEP_PATH }}'
        # https://docs.github.com/en/actions/learn-github-actions/contexts
        jq -Mcre 'del(.token)|del(.event)|{github:.}' <<< "$STEP_CTX_GITHUB" | kit::json::flatten | kit::wf::group 'workflow context 👉 "github" without "github.event"'
        jq -Mcre '{github:{event:.event}}' <<< "$STEP_CTX_GITHUB" | kit::json::flatten | kit::wf::group 'workflow context 👉 "github.event"'
        jq -Mcre '{runner:.}' <<< "$STEP_CTX_RUNNER" | kit::json::flatten | kit::wf::group 'workflow context 👉 "runner"'
...
