name: Continuous Integration

on:
  workflow_dispatch:
  push:
    paths:
    - 'Dockerfile'
    - '.dockerignore'

jobs:
  call-workflow-build-and-push:
    id: build-and-push
    uses: vbem/reusable-workflows/.github/workflows/build-and-push.yml@main
    secrets:
      token: ${{ secrets.DOCKERHUB_TOKEN }}
  
  
