name: Continuous Integration

on:
  workflow_dispatch:
  push:
    paths:
    - 'Dockerfile'
    - '.dockerignore'

jobs:
  build:
    uses: vbem/reusable-workflows/.github/workflows/image-ci.yml@main
    with:
      ctx:    .
      host:   docker.io
      user:   ${{ github.repository_owner }}
      repo:   ${{ github.repository }} 
      tag:    ''
      latest: false
      test:   lll
    secrets:
      token:  ${{ secrets.DOCKERHUB_TOKEN }}
  
        
