name: Continuous Integration

on:

  workflow_dispatch:
    inputs:
      img_tag:  
        description: 'Image tag'
        type: string
        required: false
        default: ''
      img_latest:
        description: 'Whether to push latest tag'
        type: boolean
        required: false
        default: 'false'
    
  push:
    paths:
    - 'Dockerfile'
    - '.dockerignore'
    - 'src/**'
    
env:
  TZ:             Asia/Shanghai
  WF_CR_HOST:     docker.io
  WF_CR_USER:     ${{ github.repository_owner }}
  WF_CR_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}
  WF_IMG_REPO:    ${{ github.repository }}

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
   
    - name: Gather context -> github
      run: |        
        cat | jq 'del(.token)' > context.github.json <<__EOF__
        ${{ toJSON(github) }}
        __EOF__
        
    - name: Gather context -> runner
      run: |
        cat > context.runner.json <<__EOF__
        ${{ toJSON(runner) }}
        __EOF__
        
    # - uses: actions/checkout@v3
    
    #- uses: docker/login-action@v1
    #  with:
    #    registry: ${{ env.WF_CR_HOST }}
    #    username: ${{ env.WF_CR_USER }}
    #    password: ${{ env.WF_CR_TOKEN }}
    
    - name: Generate image tag and URI
      id: gen
      run: |
        if [[ -n "${{ github.event.inputs.tag }}" ]]; then
          tag='${{ github.event.inputs.tag }}'
        elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
          tag="$(basename ${{ github.ref }})"
        else
          tag=$(TZ=CST+8 date +'%y.%m.%d')-$(echo ${{ github.sha }}|cut -c-7)
        fi
        echo "Tag of image will be: $tag"
        echo "::set-output name=tag::$tag"
        
        uri=${{ env.WF_CR_HOST }}/${{ env.WF_IMG_REPO }}:$tag
        echo "URI of image will be: $uri"
        echo "::set-output name=uri::$uri"
        
        created="$(TZ=CST+8 date --rfc-3339=seconds)"
        echo "Created of image will be: $created"
        echo "::set-output name=created::$created"
        
    - uses: docker/build-push-action@v2
      with:
        pukk: true
        tags: ${{ steps.gen.outputs.uri }}
        build-args: |
          IMG_CREATED=${{ steps.gen.outputs.created }}
          IMG_VER=${{ steps.gen.outputs.tag }}
          IMG_REV=${{ github.sha }}
        
    - run: |
        docker image inspect ${{ steps.gen.outputs.uri }}
#  build:
#    uses: vbem/reusable-workflows/.github/workflows/image-ci.yml@main
#    with:
#      ctx:    .
#      host:   docker.io
#      user:   ${{ github.repository_owner }}
#      repo:   ${{ github.repository }} 
#      tag:    ''
#      latest: true
#      test:   cat /etc/os-release
#    secrets:
#      token:  ${{ secrets.DOCKERHUB_TOKEN }}
  
        
