name: Continuous Integration

on:
  workflow_dispatch:
  push:
    paths:
    - 'Dockerfile'
    - '.dockerignore'

jobs:
  build:
    uses: vbem/reusable-workflows/.github/workflows/image-ci.yml@main
    with:
      ctx:    .
      host:   docker.io
      user:   ${{ github.repository_owner }}
      repo:   ${{ github.repository }} 
      tag:    ''
      latest: false
    secrets:
      token:  ${{ secrets.DOCKERHUB_TOKEN }}
  
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      JOB_TAG:    ${{ needs.build.outputs.tag }}
      JOB_URI:    ${{ needs.build.outputs.uri }}
      JOB_HOST:   docker.io
      JOB_USER:   ${{ github.repository_owner }}
      JOB_REPO:   ${{ github.repository }}
      JOB_TOKEN:  ${{ secrets.DOCKERHUB_TOKEN }}
      
    steps:
    
    - name: Gather GitHub context information
      run: |
        cat > context.needs.build.outputs.json <<EOF
        ${{ toJSON(needs.build.outputs) }}
        EOF
        cat | jq 'del(.token)' > context.github.json <<EOF
        ${{ toJSON(github) }}
        EOF
        cat > context.runner.json <<EOF
        ${{ toJSON(runner) }}
        EOF
      
    - name: Login container registry
      run: |
        docker login ${{ env.JOB_HOST }} -u ${{ env.JOB_USER }} -p ${{ env.JOB_TOKEN }}
        
    - name: Pull image
      run: |
        docker pull ${{ env.JOB_URI }}
        
    - name: Test image
      run: |
        docker run --rm ${{ env.JOB_URI }} yq -V
        
