name: Continuous Integration

on:
  workflow_dispatch:
  push:
    paths:
    - 'Dockerfile'
    - '.dockerignore'
    
env:
  WF_BUILD_CTX:  .
  WF_CR_HOST:    docker.io
  WF_CR_USER:    ${{ github.repository_owner }}
  WF_CR_TOKEN:   &TOKEN ${{ secrets.DOCKERHUB_TOKEN }}
  WF_CR_REPO:    ${{ github.repository }} 

jobs:
  build:
    uses: vbem/reusable-workflows/.github/workflows/image-builder.yml@main
    secrets:
      token:  *TOKEN
  
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      JOB_IMG_URI: ${{ needs.call-workflow-build-and-push.outputs.uri }}
      
    steps:
    
    - name: Gather GitHub context information
      run: |
        cat > context.needs.build.outputs.json <<EOF
        ${{ toJSON(needs.build.outputs) }}
        EOF
        cat | jq 'del(.token)' > context.github.json <<EOF
        ${{ toJSON(github) }}
        EOF
        cat > context.runner.json <<EOF
        ${{ toJSON(runner) }}
        EOF
      
    - name: Checkout code repository
      uses: actions/checkout@v2
      
    - name: Login container registry
      run: |
        docker login ${{ env.WF_CR_HOST }} -u ${{ env.WF_CR_USER }} -p ${{ env.WF_CR_TOKEN }}
        
    - name: Pull image
      run: |
        docker pull $JOB_IMG_URI
        
    - name: Test image
      run: |
        docker run --rm -it $JOB_IMG_URI yq -V
        
