name: Continuous Integration

on:
  workflow_dispatch:
  push:
    paths:
    - 'Dockerfile'
    - '.dockerignore'

jobs:
  call-workflow-build-and-push:
    uses: vbem/reusable-workflows/.github/workflows/build-and-push.yml@main
    secrets:
      token: ${{ secrets.DOCKERHUB_TOKEN }}
  
  show-builder-outputs:
    runs-on: ubuntu-latest
    needs: call-workflow-build-and-push
    steps:
    - run: |
        cat <<EOF
        ${{ toJSON(needs.call-workflow-build-and-push.outputs) }}
        EOF
