name: Continuous Integration

on:
  workflow_dispatch:
  push:
    paths:
    - 'Dockerfile'
    - '.dockerignore'

jobs:
  build:
    uses: vbem/reusable-workflows/.github/workflows/image-builder.yml@main
    with:
      ctx:    .
      host:   docker.io
      user:   ${{ github.repository_owner }}
      repo:   ${{ github.repository }} 
      tag:    ''
      latest: true
    secrets:
      token:  ${{ secrets.DOCKERHUB_TOKEN }}
  
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      JOB_URI:  ${{ needs.build.outputs.uri }}
      
    steps:
    
    - name: Gather GitHub context information
      run: |
        cat > context.needs.build.outputs.json <<EOF
        ${{ toJSON(needs.build.outputs) }}
        EOF
        cat | jq 'del(.token)' > context.github.json <<EOF
        ${{ toJSON(github) }}
        EOF
        cat > context.runner.json <<EOF
        ${{ toJSON(runner) }}
        EOF
      
    - name: Login container registry
      run: |
        docker login  ${{ needs.build.outputs.host }} -u  ${{ needs.build.outputs.user }} -p  ${{ needs.build.outputs.token }}
        
    - name: Pull image
      run: |
        docker pull  ${{ needs.build.outputs.uri }}
        
    - name: Test image
      run: |
        docker run --rm -it ${{ needs.build.outputs.uri }} yq -V
        
