name: Continuous Integration

on:

  workflow_dispatch:
    inputs:
      img_tag:  
        description: 'Image tag'
        type: string
        required: false
        default: ''
      img_latest:
        description: 'Boolean if latest tag will be also pushed'
        type: boolean
        required: false
        default: 'false'
    
  push:
    paths:
    - 'Dockerfile'
    - '.dockerignore'
    - 'src/**'
    
env:
  WF_BUILD_CTX:   .
  WF_CR_HOST:     docker.io
  WF_CR_USER:     ${{ github.repository_owner }}
  WF_CR_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}
  WF_IMG_REPO:    ${{ github.repository }}

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
   
    - name: Gather context -> github
      run: |        
        cat | jq 'del(.token)' > context.github.json <<__EOF__
        ${{ toJSON(github) }}
        __EOF__
        
    - name: Gather context -> runner
      run: |
        cat > context.runner.json <<__EOF__
        ${{ toJSON(runner) }}
        __EOF__
        
    - name: Gather context -> job
      run: |        
        cat > context.job.json <<__EOF__
        ${{ toJSON(job) }}
        __EOF__
        
    - name: Gather context -> steps
      run: |        
        cat > context.steps.json <<__EOF__
        ${{ toJSON(steps) }}
        __EOF__
    
    - uses: actions/checkout@v2
    
    - uses: docker/login-action@v1
      with:
        registry: ${{ env.WF_CR_HOST }}
        username: ${{ env.WF_CR_USER }}
        password: ${{ env.WF_CR_TOKEN }}
    
    
#  build:
#    uses: vbem/reusable-workflows/.github/workflows/image-ci.yml@main
#    with:
#      ctx:    .
#      host:   docker.io
#      user:   ${{ github.repository_owner }}
#      repo:   ${{ github.repository }} 
#      tag:    ''
#      latest: true
#      test:   cat /etc/os-release
#    secrets:
#      token:  ${{ secrets.DOCKERHUB_TOKEN }}
  
        
