name: Lint Code Base

on:
  push:
    branches: [master, main]
  workflow_dispatch:
  
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # https://github.com/marketplace/actions/super-linter
      - uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false # only new or edited files will be parsed for validation.
          VALIDATE_GITHUB_ACTIONS: false # disable the linting process of the GitHub Actions.
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
